### ISSUE TITLE
Joins the wrong Google Meet meeting

### ISSUE THREAD

**Issue by nicklooijmans** [ellenli/up-next#10]
I was testing the app and in the menu bar it said `[meeting name] in 18 minutes`, and when I clicked `Join via Google Meet` it joined the hangout of a meeting that's currently ongoing, not the one that's displayed in the menu bar.

**Comment by ellenli** [comment]
Thanks for catching that @nicklooijmans! Will definitely fix this for v1.0.

**Comment by ellenli** [comment]
[Bug has been fixed in version 1.0](https://apps.apple.com/us/app/up-next/id1355117041?ls=1&mt=12) - enjoy!
