### ISSUE TITLE
Ability to Open in Non-Default Browser

### ISSUE THREAD

**Issue by waxidiotic** [ellenli/up-next#11]
Firefox is my default browser on my Mac but it obviously doesn't support Hangouts/Meet - it would be cool to have the ability to always open meetings in Chrome, even if another browser is the default.

**Comment by waxidiotic** [comment]
Oops, didn't see #1 because it was closed.

**Comment by ellenli** [comment]
This has already been fixed! Did you download the app from the App Store? Are you still experiencing the issue?

**Comment by waxidiotic** [comment]
@ellenli yeah, i saw issue #1 after i submitted this one so i closed it. the options to join the meets are disabled in the up-next menu but i havent really tried to troubleshoot yet. if i still have problems, i'll let you know.
