### ISSUE TITLE
Showing declined/spam events with iCal

### ISSUE THREAD

**Issue by dcousineau** [ellenli/up-next#12]
There has been a spate of iCal spam where, due to iCal's automatic adding of events from emails (even those in spam) (see articles like [this one on wired](http://www.wired.co.uk/article/calendar-spam-apple)). When I pointed up next to my icloud calendar it showed declined spam invites:

![screen shot 2018-03-21 at 1 26 35 pm](https://user-images.githubusercontent.com/30331/37726439-be8542fc-2d0b-11e8-82a8-3a2cb479da53.png)

Which are clearly declined as seen here:

![screen shot 2018-03-21 at 1 26 57 pm](https://user-images.githubusercontent.com/30331/37726451-c5eac580-2d0b-11e8-806a-bfc8120eec3d.png)

It looks like upnext is showing declined events possibly? Something to look in to!

**Comment by ellenli** [comment]
Yikes. Thanks for flagging this!

**Comment by bradsokol** [comment]
I'm also seeing declined meetings in Up-Next. In my case, the meeting was legit (i.e. not spam as described above). The invitation was through Google calendar.

**Comment by ellenli** [comment]
Done - will be part of the Up Next 1.0 release.
