### ISSUE TITLE
Add support for Zoom

### ISSUE THREAD

**Issue by ellenli** [ellenli/up-next#13]
Shortcuts and quick-links currently only support Google Meet but lots of folks use Zoom, Join.me and Gotomeeting instead!

**Comment by angelcustodio** [comment]
Super interested on having this feature in the app, you're doing a great job!
If you need any help, don't hesitate to ask :)

**Comment by goetzchr** [comment]
This would be awesome :)

**Comment by ellenli** [comment]
Done - will be part of the Up Next 1.0 release.
