### ISSUE TITLE
Launch app on login/startup

### ISSUE THREAD

**Issue by ellenli** [ellenli/up-next#2]

**Comment by tclayson** [comment]
> As a work-around, adding "up-next" to your Login Items in the Users & Groups system preferences achieves the same result.

This isn't possible for me as my company has locked down that section of the Settings App. I'd love this option built into the app.

Thanks!

**Comment by Stanzilla** [comment]
yes plese

**Comment by ellenli** [comment]
Done - will be part of the Up Next 1.0 release.
