### ISSUE TITLE
Support Google Meet URL in the event description

### ISSUE THREAD

**Issue by nilbus** [ellenli/up-next#20]
Most of my recurring meetings unfortunately have the Google Meet link in the description, not in the field where perhaps it ought to be. Lacking a meeting in the usual place, could you also scan for a matching meet URL in the description?

Thanks!

**Comment by ellenli** [comment]
Totally! Great idea, thanks.

**Comment by ellenli** [comment]
Done - will be part of the Up Next 1.0 release.
