### ISSUE TITLE
Accidentally clicked 'Don't allow' for calendar sync; app stuck on 'Loading...'

### ISSUE THREAD

**Issue by isinsusakalli** [ellenli/up-next#21]
When I first launched it, I clicked ‘Don’t allow’ for synching with calendar. I tried uninstalling and re-installing again and it won’t let me pick again. 
It is now stuck at Loading... and I don’t know how to link it to a calendar.
<img width="266" alt="screen shot 2018-03-26 at 12 43 17 pm" src="https://user-images.githubusercontent.com/29760062/37920181-2d5c26dc-30f4-11e8-9292-8096e255b77b.png">

**Comment by ellenli** [comment]
Thanks so much for that tip @vinibaggio! 👍 That should fix it for you @isinsusakalli.
