### ISSUE TITLE
Mark optional meetings as "(optional)"

### ISSUE THREAD

**Issue by t6d** [ellenli/up-next#22]
In the case of overlapping meetings, it would be nice if Up Next would prioritize the meetings where your attendance is mandatory over those where it is optional.

**Comment by ellenli** [comment]
Update: just addressed https://github.com/ellenli/up-next/issues/12 so *declined events will no longer show up* effective next release (1.0). If you have overlapping meetings, accepting/declining them would solve the prioritization issue.
