### ISSUE TITLE
Updated meeting time isn't reflected in app

### ISSUE THREAD

**Issue by devshahani** [ellenli/up-next#23]
I changed a meeting time from 1.30pm to 11.15am but the updated meeting time isn't reflected in the app. I tried quitting the app and opening it again but it still shows the old meeting time. 

Up-next app:
![](https://screenshot.click/06-01-fokk9-hvi45.jpg)

Google cal:
![](https://screenshot.click/06-03-1zrxf-qhkut.jpg)

**Comment by arlo-j** [comment]
I'd add that my calendar isn't refreshing in Up Next unless I quit and reopen Up Next.  New events, changed times, none of it seems to update post-launch until a forced reopen.

**Comment by Manzanit0** [comment]
For the record, I'd add too that when an event is deleted, it will still show even if exiting and re-launching the app.

**Comment by ellenli** [comment]
Thanks for flagging this bug - fix [in version 1.0](https://apps.apple.com/us/app/up-next/id1355117041?ls=1&mt=12). Enjoy!
