### ISSUE TITLE
Support for default browser instead of Chrome

### ISSUE THREAD

**Issue by jessebc** [ellenli/up-next#31]
Brave is a browser based on Chrome but has ad blocking and anti-tracking features built in. 

I have it set as my default browser and expected that Up Next would open up links in Brave, but instead Up Next opens links in Chrome.

**Comment by aredridel** [comment]
Likewise, I'd prefer to use my default browser — Firefox in my case.

**Comment by ellenli** [comment]
Done - will be part of the Up Next 1.0 release.

**Comment by aredridel** [comment]
You're the best! (and this tool is :100:)
