### ISSUE TITLE
Disable all keyboard shortcuts

### ISSUE THREAD

**Issue by benjaminsehl** [ellenli/up-next#33]
Hey there — love the idea of the app, but unfortunately a major issue is the hotkey support! In VS code, Command J toggles the Terminal, which is crucial for me! So having that get overridden by up-next is pretty frustrating. Any way to change that hotkey/add a preference pane/disable entirely/etc?

Cheers!

**Comment by abdulajet** [comment]
yeah great app @ellenli  but command + shift + J is used in Xcode so it would be great to be able to disable that.

**Comment by cameronsstone** [comment]
Yeah, Outlook uses command-J for forwarding email. I'm sad - I really like this app's functionality (apart from not being a gsuite user).

**Comment by cameronsstone** [comment]
You can't disable the hotkey, but you can change it. Use System Prefs -> Keyboard -> Shortcuts -> App Shortcuts, and change it to something that doesn't overlap.

You have to quit sysprefs, and restart up-next.app to get it to pick up the new binding.

Ellen, please still add preferences to disable the google meet integration - I can't use it, and don't want to see it in the interface (or using up global shortcuts).

Thanks for a great app!

**Comment by ellenli** [comment]
Custom shortcuts are captured via https://github.com/ellenli/up-next/issues/7. I've changed this issue to disable all shortcuts and that should do the trick for most people most of the time.

I'll get this in the next release. Thanks!

**Comment by abdulajet** [comment]
Thanks!

**Comment by ellenli** [comment]
Thanks for flagging! Keyboard shortcuts are now disabled by default [in version 1.0](https://apps.apple.com/us/app/up-next/id1355117041?ls=1&mt=12). Enjoy!
