### ISSUE TITLE
Meeting links are hardcoded with {{shopify.com}} URLs

### ISSUE THREAD

**Issue by timfee** [ellenli/up-next#35]
Whenever I click a meeting link, it directs me to: https://hangouts.google.com/hangouts/_/shopify.com/xxxxxxxx - even though Google figures it out, still should probably avoid the redirect

**Comment by timfee** [comment]
Pretty sure the canonical URL format ends up being https://meet.google.com/xxx-xxx-xxx these days. :)

**Comment by ellenli** [comment]
Thanks! Fixed and will be part of the Up Next 1.0 release.
