### ISSUE TITLE
Use user's default browser (or let them pick a browser)

### ISSUE THREAD

**Issue by syropian** [ellenli/up-next#38]
I use Brave as my default browser, and noticed it opened my meeting up in Chrome 😅 

If I could choose the browser, that'd be super, as I actually use Firefox for all my Google meetings, because it's the only browser where my webcam doesn't lag 🤔 

Thanks for the great app!

**Comment by ellenli** [comment]
Duplicate of #31. Fixed and will be part of the Up Next 1.0 release.
