### ISSUE TITLE
Crash with recurring event

### ISSUE THREAD

**Issue by mnorrisvuw** [ellenli/up-next#41]
When switching to my Exchange calendar, Up-Next crashes with the following Console error:

`Looping a suspicious number of times in -[CoreRecurrenceRule expandFastPathDatesInCalendar:(gregorian) recurrenceStart:(Mon Sep 14 15:30:00 2015) expansionRange:(Mon May 18 07:36:15 2020, Tue May 19 00:00:02 2020)]

self = [N](5029,{
    "X-WR-BYDAY" =     (
        "CALWeekNumber d:1 n:0"
    );
    "X-WR-INTERVAL" = 1;
    "X-WR-WEEKSTART" = 1;
}) change:(0,{
}){CALREC:CALWeeklyRecurrence}

currentDate before = Sat Jun  9 15:30:00 2018
deltaInterval = <NSDateComponents: 0x600003fbb020>
    Day: 1000
currentDate after = Sun Jun 10 15:30:00 2018`

**Comment by ellenli** [comment]
Should be fixed [in version 1.0](https://apps.apple.com/us/app/up-next/id1355117041?ls=1&mt=12) - please let me know if you continue to encounter this issue!
