### ISSUE TITLE
Pick default browser in the OS

### ISSUE THREAD

**Issue by Manzanit0** [ellenli/up-next#42]
First of all, great work on this! I'm finding it tremendously useful in my day to day :)

As for the bug report, currently it always opens Chrome, although the default is Safari.

**Comment by peterhartman** [comment]
I am seeing the same problem when my default browser is Brave

**Comment by ellenli** [comment]
Thanks for flagging! [It's been fixed in version 1.0](https://apps.apple.com/us/app/up-next/id1355117041?ls=1&mt=12), all links should now open in the default browser.

**Comment by aredridel** [comment]
Sweet!
