### ISSUE TITLE
Not display declined events

### ISSUE THREAD

**Issue by Manzanit0** [ellenli/up-next#43]
Not sure if it's the intended behaviour, but I thought I'd pop it just in case. Basically, it still shows all declined events, which makes it a bit confusing as in to what's really up next.

**Comment by Joshuasony** [comment]
Same issue here.

**Comment by ellenli** [comment]
[Fixed in version 1.0!](https://apps.apple.com/us/app/up-next/id1355117041?ls=1&mt=12)
