### ISSUE TITLE
Hardcoded 'shopify.com' Google domain space

### ISSUE THREAD

**Issue by jmedwards** [ellenli/up-next#45]
When I open a Google Meet link using Up Next, I first get sent to the /shopify.com/ Google Apps domain before being redirected to my own. I wonder if 'shopify.com' is hardcoded into the Meet URL here.

<img width="491" alt="Screenshot 2020-05-26 at 18 33 18" src="https://user-images.githubusercontent.com/132245/82931798-61e0b200-9f7f-11ea-8b78-2d4ed6f884e1.png">

**Comment by timfee** [comment]
I reported this in #35 and I think it's on track for a fix :)

**Comment by ellenli** [comment]
Yep! It's been fixed for the next release. Thanks!
