### ISSUE TITLE
Purchased Pro: Have to restore my purchase and re-do my settings every time I restart my computer

### ISSUE THREAD

**Issue by pllgr** [ellenli/up-next#52]
I paid for the Pro version. 

Now everytime I restart my computer, it forgets I have the Pro version. I have to:
- go into settings and Restore the Purchase
- Re-do all my settings such as what to show when I don't have meetings

Love that I can join Zoom calls directly now but it's annoying that after paying $26 CAD that I now have to set it over and over again everyday.

Of course, I don't remember to do it every morning when I boot up my computer so I end up having to do it when I most urgently need it to work (when I'm trying to join a Zoom call but instead it keeps opening my calendar)

**Comment by ellenli** [comment]
Fixed in 1.0.1, now being the App Store now so an update should be available in the next day or two. Sorry about the trouble and thank you for your patience!

**Comment by ellenli** [comment]
[Update now available.](https://apps.apple.com/us/app/up-next/id1355117041?ls=1&mt=12)

**Comment by pllgr** [comment]
It's fixed! You're a star!
