### ISSUE TITLE
Purchased Monthly Subscription, but Pro is not Enabled

### ISSUE THREAD

**Issue by jmburges** [ellenli/up-next#53]
Hello!

I purchased a monthly subscription, and I verified it on the app store. Sadly, Pro isn't enabled. I hit the "Restore Purchase" button and nothing happens though.

**Comment by ellenli** [comment]
Sorry about this issue. [Updating the app](https://apps.apple.com/us/app/up-next/id1355117041?ls=1&mt=12) might fix it - can you give that a try and report back?
