### ISSUE TITLE
Incorrect calendar is picked up

### ISSUE THREAD

**Issue by etolstoy** [ellenli/up-next#54]
Hi!
Up Next doesn't show correct events for a selected calendar. It seems, that it selects a calendar randomly. I have ~15 calendars added if it helps ¯\_(ツ)_/¯ 

<img width="1269" alt="Screenshot 2021-01-13 at 12 08 39" src="https://user-images.githubusercontent.com/3955262/104430728-1fb0c300-5598-11eb-959b-948b7c34d98d.png">
<img width="491" alt="Screenshot 2021-01-13 at 12 08 46" src="https://user-images.githubusercontent.com/3955262/104430735-217a8680-5598-11eb-8cda-abb5ac2a4291.png">
<img width="205" alt="Screenshot 2021-01-13 at 12 08 50" src="https://user-images.githubusercontent.com/3955262/104430742-23444a00-5598-11eb-8833-7160d16aafb1.png">

**Comment by etolstoy** [comment]
That's fun. When I restart the app the calendar selection is changed to the one with those events showed in the last screenshot.

**Comment by ellenli** [comment]
Thanks for reporting. This bug has been fixed in 1.0.1 - rolling out to the App Store today. 🙏

**Comment by ellenli** [comment]
[Update now available.](https://apps.apple.com/us/app/up-next/id1355117041?ls=1&mt=12)

**Comment by prashantpsr24** [comment]
I am experiencing this issue even after the update.
I have events on my calendar, but it shows No upcoming meetings.

Verified I have provided permissions to Up next in Privacy settings.
Uninstalled and Installed again too.
Changed calendar in preferences.
