### ISSUE TITLE
No longer shows up in Menu Bar?

### ISSUE THREAD

**Issue by jmburges** [ellenli/up-next#63]
Hello!

I used Up Next for a while until about a year ago when my Mac broke. I recently bought a new M1 Pro MacBook and Up Next shows it's running, but there is nothing in the menubar.

**Comment by ellenli** [comment]
What other apps do you have in the menu bar? My first guess is Up Next might be hidden/truncated which can happen when you have other apps in the menu bar, or if the event name is too long, in either case it overflows. If this is the case you can try re-ordering menu bar items by holding down `command` and dragging.

**Comment by jmburges** [comment]
I played around with stuff and it looks like it just works now. Not sure what the issue is!
