### ISSUE TITLE
Be able to replace ⌘J with a custom shortcut

### ISSUE THREAD

**Issue by matt-from-toronto** [ellenli/up-next#7]
⌘-J is a popular shortcut in text editors to join two lines. If I have up-next running I can't use this shortcut in my text editor. 

Thanks for making up-next, seems quite useful.

**Comment by mattvleming** [comment]
You could potentially allow this through this Systems Preferences tab:

![screen shot 2018-03-20 at 11 00 10 am](https://user-images.githubusercontent.com/2602218/37662647-e0fa28ae-2c2d-11e8-9d10-91ccaf26859b.png)

**Comment by dengjeffrey** [comment]
👍⌘-J is also a shortcut in Xcode, would be nice to be able to disable or change the hotkeys for the app

**Comment by rianrainey** [comment]
Adding Evernote's Quick Jump hotkey and Outlook for Mac's forwarding hotkey.

Making this global is rather invasive for a very specific use-case (using Google Meet).

**Comment by OlivierMrz** [comment]
Yes, it would be nice to change to a custom hotkey 😕

**Comment by jtgrenz** [comment]
Also affects photoeditors. I was so confused as to why Capture One wasn't letting me move photos to my selected photos folder or why Finder wasn't showing me view options. I'd love to be able to just unset the shortcut all together. I don't think its something that needs to be globally bound, at least not for me.  I'd like to just join a meeting by clicking the menubar icon.

**Comment by jtgrenz** [comment]
hmm, tried to set the shortcut to something else in System Preferences > Keyboard, but I guess because Up-Next is a menu bar app, its never the foremost app, so the app specific shortcut never connects to the app and it still listens for Cmd-J

[![alt](https://screenshot.click/28-07-ynwgb-oowlo.jpg)](https://screenshot.click/28-07-ynwgb-oowlo.jpg)

Still swallows Cmd-J globally despite being reassigned.

**Comment by lukelabonte** [comment]
⌘-J is also a shortcut in Finder that gets eaten too. I would love a way to be able to disable shortcuts completely for Up Next.

**Comment by ellenli** [comment]
Custom shortcuts have been [added to version 1.0](https://apps.apple.com/us/app/up-next/id1355117041?ls=1&mt=12) - enjoy!
